IF
	OnCreation()
	Global("pxjjsazon","LOCALS",0)
THEN
	RESPONSE #95
		MakeGlobal()
		ChangeEnemyAlly(Myself,FAMILIAR)
		AddFamiliar()
		SetGlobal("pxjjsazon","LOCALS",1)
	RESPONSE #5
		ChangeEnemyAlly(Myself,ENEMY)
		SetGlobal("pxjjsazon","LOCALS",1)
END

IF
    Die()
THEN
    RESPONSE #100
         GiveItemCreate("pxjcoeur",Player1,0,0,0)
END

IF
	XPGT(Player1,4999999)
	Global("pxjjsezwepon","LOCALS",0)
THEN
	RESPONSE #100
	ReallyForceSpellRES("pxjjenc5",Myself)
	SetGlobal("pxjjsezwepon","LOCALS",1)
END

IF
	XPGT(Player1,3999999)
	Global("pxjjsezwepon","LOCALS",0)
THEN
	RESPONSE #100
	ReallyForceSpellRES("pxjjenc4",Myself)
	SetGlobal("pxjjsezwepon","LOCALS",1)
END

IF
	XPGT(Player1,2999999)
	Global("pxjjsezwepon","LOCALS",0)
THEN
	RESPONSE #100
	ReallyForceSpellRES("pxjjenc3",Myself)
	SetGlobal("pxjjsezwepon","LOCALS",1)
END

IF
	XPGT(Player1,1999999)
	Global("pxjjsezwepon","LOCALS",0)
THEN
	RESPONSE #100
	ReallyForceSpellRES("pxjjenc2",Myself)
	SetGlobal("pxjjsezwepon","LOCALS",1)
END

IF
	XPGT(Player1,999999)
	Global("pxjjsezwepon","LOCALS",0)
THEN
	RESPONSE #100
	ReallyForceSpellRES("pxjjenc1",Myself)
	SetGlobal("pxjjsezwepon","LOCALS",1)
END

IF
	Heard([ANYONE],111)
THEN
	RESPONSE #100
		MoveToObject(NearestEnemyOf(Myself))
END

IF
  ActionListEmpty()
  See(Nearestenemyof(Myself))
THEN
  RESPONSE #100
    AttackReevaluate(Nearestenemyof(Myself),30)
END

IF
	HotKey(D)
	!See(Player1)
THEN
  RESPONSE #100
    MoveToObject(Player1)
END

IF
  ActionListEmpty()
  AttackedBy([0],DEFAULT)
THEN
  RESPONSE #100
    Attack(Lastattackerof(Myself))
END